### ISSUE TITLE
docker deploy manage.py migrate FAILS

### ISSUE THREAD

**Issue by claudyus** [openwisp/nodeshot#1]
migrations fails under dokku, further investigation needed. 
@nemesisdesign any idea. missed deps?

```
$ git push deploy docker:master
[...]
Successfully installed Django-1.6.11 Pillow-2.9.0 PyJWT-1.3.0 PyYAML-3.11 amqp-1.4.6 anyjson-0.3.3 backports.ssl-match-hostname-3.4.0.2 billiard-3.3.0.20 blessings-1.6 bpython-0.14.2 celery-3.1.17 certifi-2015.4.28 curtsies-0.1.19 decorator-3.4.2 django-appconf-1.0.1 django-celery-email-1.1.1 django-cors-headers-1.0.0 django-debug-toolbar-1.3.2 django-extensions-1.5.5 django-filebrowser-3.5.7 django-grappelli-2.5.3 django-hstore-1.4 django-leaflet-0.15.2 django-netfields-0.2.2 django-redis-4.2.0 django-rest-swagger-0.3.2 django-reversion-1.8.2 django-rosetta-0.7.6 django-smuggler-0.4.1 djangorestframework-2.4.5 djangorestframework-gis-0.7 djangorestframework-hstore-1.1 drf-extensions-0.2.5 ecdsa-0.13 geojson-elevation-0.1 greenlet-0.4.7 influxdb-2.6.0 jsonfield-1.0.3 kombu-3.0.26 libcnml-0.9.2 markdown-2.6.2 microsofttranslator-0.5 mimeparse-0.1.3 msgpack-python-0.4.6 netaddr-0.7.15 netdiff-0.4.1 netengine-0.1a0 networkx-1.9.1 oauthlib-0.7.2 paramiko-1.15.2 polib-1.0.6 psycopg2-2.6.1 pyasn1-0.1.8 pycrypto-2.6.1 pygments-2.0.2 pysnmp-4.2.5 python-dateutil-2.4.2 python-openid-2.2.5 python-social-auth-0.2.10 pytz-2015.4 raven-5.3.1 redis-2.10.3 requests-2.7.0 requests-oauthlib-0.5.0 simplejson-3.7.3 six-1.9.0 south-1.0.2 sqlparse-0.1.15 tld-0.7.2 tornado-4.2
 ---> 3b0db0c0e85b
Removing intermediate container 43aafbaac3b3
Step 5 : ADD . /app
 ---> d9d65b8634e6
Removing intermediate container 19b7d30c6905
Step 6 : COPY docker/ /app/
 ---> 496826730cf9
Removing intermediate container 7abdfe9dba57
Step 7 : RUN mkdir /log
 ---> Running in 64f0b8abccf3
 ---> e836179aacb0
Removing intermediate container 64f0b8abccf3
Step 8 : CMD python manage.py migrate && python manage.py runserver
 ---> Running in 22d2ca109402
 ---> e2c8468cfadd
Removing intermediate container 22d2ca109402
Successfully built e2c8468cfadd
-----> Releasing nodeshot...
-----> Deploying nodeshot...
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> nodeshot container output:
       Traceback (most recent call last):
         File "manage.py", line 10, in <module>
           execute_from_command_line(sys.argv)
         File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
           utility.execute()
         File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
           self.execute(*args, **options.__dict__)
         File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
           output = self.handle(*args, **options)
         File "/usr/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
           ignore_ghosts = ignore_ghosts,
         File "/usr/local/lib/python2.7/site-packages/south/migration/__init__.py", line 200, in migrate_app
           applied_all = check_migration_histories(applied_all, delete_ghosts, ignore_ghosts)
         File "/usr/local/lib/python2.7/site-packages/south/migration/__init__.py", line 79, in check_migration_histories
           for h in histories:
         File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
           self._fetch_all()
         File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
           self._result_cache = list(self.iterator())
         File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
           for row in compiler.results_iter():
         File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
           for rows in self.execute_sql(MULTI):
         File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
           cursor.execute(sql, params)
         File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
           return self.cursor.execute(sql, params)
         File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
           six.reraise(dj_exc_type, dj_exc_value, traceback)
         File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
           return self.cursor.execute(sql, params)
       django.db.utils.ProgrammingError: relation "south_migrationhistory" does not exist
       LINE 1: ...gration", "south_migrationhistory"."applied" FROM "south_mig...
                                                                    ^
=====> end nodeshot container output
remote: /usr/local/bin/dokku: line 49: 32177 Killed                  dokku deploy "$APP"
To dokku@dokku.rd.unidata.it:nodeshot
 ! [remote rejected] docker -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku.rd.unidata.it:nodeshot'
```

**Comment by nemesifier** [comment]
`syncdb` is missing (must go before `migrate`)

**Comment by claudyus** [comment]
Fixed as suggested

**Comment by nemesifier** [comment]
:+1:
